language: python
dist: trusty
sudo: required
python:
  - 2.7
env:
  - DISPLAY=:99.0
addons:
  apt:
    packages:
      - python-dev
      - libsdl-image1.2-dev
      - libsdl-mixer1.2-dev
      - libsdl-ttf2.0-dev
      - libsdl1.2-dev
      - python-numpy
      - libportmidi-dev
      - libswscale-dev
      - libavformat-dev
      - libavcodec-dev
      - libjpeg-dev
      - libtiff4-dev
      - libx11-6
      - libx11-dev
      - xfonts-base
      - xfonts-100dpi
      - xfonts-75dpi
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libsmpeg-dev xfonts-cyrillic
  - sh -e /etc/init.d/xvfb start
virtalenv:
  system_site_packages: true
script: 
  - nosetests --with-coverage --cover-package=chip8
after_success:
  - coveralls
