language: python
sudo: false
python:
  - 2.7
env:
  - DISPLAY=:99.0
addons:
  apt:
    packages:
      - python-dev
      - libsdl-image1.2-dev
      - libsdl-mixer1.2-dev
      - libsdl-ttf2.0-dev
      - libsdl1.2-dev
      - python-numpy
      - libportmidi-dev
      - libswscale-dev
      - libavformat-dev
      - libavcodec-dev
      - libjpeg-dev
      - libtiff5-dev
      - libx11-6
      - libx11-dev
      - xfonts-base
      - xfonts-100dpi
      - xfonts-75dpi
      - libsmpeg-dev
      - xfonts-cyrillic
services:
  - xvfb
virtalenv:
  system_site_packages: true
script: 
  - nosetests -v --with-coverage --cover-package=chip8
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
